extends RefCounted
class_name HSMEState

const ROOT = "ROOT"
const idle := "idle"
const awakening := "awakening"
const life := "life"
const phase_1 := "phase_1"
const chill_1 := "chill_1"
const orbiting := "orbiting"
const pursuit_1 := "pursuit_1"
const combat_1 := "combat_1"
const scare_off := "scare_off"
const gapclose := "gapclose"
const attack_series := "attack_series"
const attack_1 := "attack_1"
const attack_2 := "attack_2"
const attack_3 := "attack_3"
const attack_4 := "attack_4"
const attack_5 := "attack_5"
const attack_6 := "attack_6"
const phase_switch := "phase_switch"
const phase_2 := "phase_2"
const pursuit := "pursuit"
const kick := "kick"
const elbow := "elbow"
const shoulder_kick := "shoulder_kick"
const slash_4 := "slash_4"
const slash_5 := "slash_5"
const slash_7 := "slash_7"
const slash_8 := "slash_8"
const death := "death"
