class_name DevLogImageGallery
extends BaseImageGallery


func get_raw_gallery_items() -> Array[GalleryItem]:
	var list_: Array[GalleryItem] = [
		GalleryItem.new("collage the beginning",
		MISC_PATH,
		"The Beginning"
		),
		GalleryItem.new("collage research",
		MISC_PATH,
		"Research",
		"A handful of useful links",
		),
		GalleryItem.new("collage cam",
		BASE_PATH,
		"Camera movement",
		),
		GalleryItem.new("collage rigs",
		BASE_PATH,
		"Rigging",
		"The hardest thing"
		),
		GalleryItem.new("collage pl",
		BASE_PATH,
		"Main character iterations",
		),
		GalleryItem.new("collage bg",
		BASE_PATH,
		"Final enemy design",
		"His name is Bob, he likes shiny things and hierarchical state machines"
		),
		GalleryItem.new("collage sunset",
		BASE_PATH,
		"Player animations",
		"Animations contain mechanics data like combo timings, also some SFX"
		),
		GalleryItem.new("collage figures",
		BASE_PATH,
		"Test fights with Bob and abstract art",
		),
		GalleryItem.new("collage colors",
		BASE_PATH,
		"Collage with shapes and colors",
		),
		GalleryItem.new("collage desert",
		BASE_PATH,
		"Core of the demo level in progress",
		),
		GalleryItem.new("collage lady",
		BASE_PATH,
		"Water Lady in progress",
		"Originally 'Figure of the dancer'. More on that in Museum Gallery"
		),
		GalleryItem.new("collage mm3",
		BASE_PATH,
		"Working on the Main menu scenery",
		),
		GalleryItem.new("collage museum t",
		BASE_PATH,
		"3D museum models",
"3D museum exhibits that formed the basis of some assets.
More info can be found in Credits and Museum Gallery",
		),
		GalleryItem.new("collage perf",
		BASE_PATH,
		"Performance issues",
		),
		GalleryItem.new("collage c",
		BASE_PATH,
		"The code",
		),
		GalleryItem.new("collage anim sfx",
		BASE_PATH,
		"SFX for interactive elements",
		"[i]Is this ... a bus depot?[/i]"
		),
		GalleryItem.new("collage wf",
		BASE_PATH,
		"Wireframe pixelated miniature",
		"[i]Eerie[/i]"
		),
		GalleryItem.new("collage wf2",
		BASE_PATH,
		"Additional wireframe landscapes",
		),
		GalleryItem.new("collage_15",
		BASE_PATH,
		"Collage with shapes and colors #2",
		),
	]
	return list_
